name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
      - name: Install Hashlink
        uses: cedx/setup-hashlink@v6
      - name: Install Haxe libraries
        run: |
          haxelib install --always hxcpp
          haxelib install --always hashlink
          haxelib install --always test.hxml
      - name: Install JS libraries
        run: npm install promises-aplus-tests
      - name: Build project (js)
        run: haxe hxml/test.js.hxml -D thenshim_js_fallback_allSettled -D thenshim_js_fallback_finally
      - name: Build project (js adapter)
        run: haxe hxml/test_adapter.js.hxml
      - name: Build project (cpp)
        run: haxe hxml/test.cpp.hxml
      - name: Build project (hl)
        run: haxe hxml/test.hl.hxml
      - name: Run tests (js)
        run: nodejs out/js/test.js
      - name: Run tests (js promise/a+)
        run: nodejs node_modules/promises-aplus-tests/lib/cli.js out/js/test_adapter.js
      - name: Run tests (cpp)
        run: ./out/cpp/TestAll-debug
      - name: Run tests (hl)
        run: hl out/hl/test.hl
